sudo: required

language: generic

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=cassinyio/base
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $REPO; fi
